apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::448704481726:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-EU6P48JTPQ67
      username: system:node:{{EC2PrivateDNSName}}
      - system:masters
      rolearn: arn:aws:iam::448704481726:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-08-05T23:46:32Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1811"
  uid: 4f172f16-4d94-4ad9-ac7d-5a7bdd2342cd
